services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: caseflow-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - caseflow_db_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: CaseFlow.Web/Dockerfile
    container_name: caseflow-api
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

      # IMPORTANT: use service name "db" inside compose network
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=caseflowdb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"

      # Your Program.cs reads Jwt:Key (=> Jwt__Key in env)
      Jwt__Key: "${JWT_KEY}"
    ports:
      - "5180:8080"
    restart: unless-stopped

volumes:
  caseflow_db_data:
